/**
 * The free-play host for THE BROKERS, and the three disciplines it keeps.
 *
 *   1. **The Ghost Price cannot leak.** It is drawn only once the claim is sold,
 *      changes no payout, and is never dramatised.
 *   2. **A broker's price does not exist before his fee is owed.** The word is
 *      generated by the ask, which is the client's mirror of invariant I4.
 *   3. **The purse is honest.** It escrows the stake like the facet does, pays
 *      exactly what the one payout rule says, and lasts one page load.
 */
import { describe, it, expect } from 'vitest';
import { createDemoBrokersHost, DEMO_OPENING_PURSE, DEMO_MIN_STAKE } from '../src/games/brokers/app/bridge/demoHost';
import type { BrokersHost, BrokersView } from '../src/games/brokers/app/bridge/types';
import { BROKER_LIST, HOUSE, feesForMask, payoutBase, type BrokerId } from '../src/games/brokers/core/market';
import { COPY } from '../src/games/brokers/app/ui/copy';

const STAKE = 20n * 10n ** 18n;

function everyString(value: unknown): string[] {
  if (typeof value === 'string') return [value];
  if (Array.isArray(value)) return value.flatMap(everyString);
  if (value && typeof value === 'object') return Object.values(value).flatMap(everyString);
  return [];
}

function nextView(host: BrokersHost, predicate: (v: BrokersView) => boolean): Promise<BrokersView> {
  const now = host.snapshot();
  if (predicate(now)) return Promise.resolve(now);
  return new Promise(resolve => {
    const unsubscribe = host.subscribe(view => {
      if (!predicate(view)) return;
      unsubscribe();
      resolve(view);
    });
  });
}

const settled = (v: BrokersView) => v.session?.isSettled === true;
const ready = (v: BrokersView) => v.session?.phase === 'waiting-player' || settled(v);
const fresh = (seed: number) => createDemoBrokersHost({ seed: [seed, 0x1728, 0xc4, 0x5e], randomnessDelayMs: 0 });

/** Asks the given brokers in order, then sells. */
async function shop(host: BrokersHost, ids: readonly BrokerId[]) {
  await host.openSession(STAKE);
  for (const id of ids) {
    await nextView(host, ready);
    await host.submitAction({ kind: 'ASK', brokerId: id });
  }
  await nextView(host, ready);
  await host.submitAction({ kind: 'TAKE' });
  const view = await nextView(host, settled);
  const session = view.session;
  if (!session) throw new Error('lost the session');
  return session;
}

describe('the ghost cannot leak', () => {
  it('is null at every point before the claim is sold', async () => {
    const host = fresh(11);
    await host.openSession(STAKE);
    for (const broker of BROKER_LIST) {
      const view = await nextView(host, ready);
      expect(view.session?.ghost, `after ${broker.name}`).toBeNull();
      await host.submitAction({ kind: 'ASK', brokerId: broker.id });
    }
    host.destroy();
  });

  it('arrives once it is sold, and names a man who was not asked', async () => {
    const host = fresh(21);
    const session = await shop(host, [2]);
    expect(session.ghost).not.toBeNull();
    expect(session.ghost?.brokerId).not.toBe(2);
    expect((session.askedMask & (1 << (session.ghost?.brokerId ?? 0))) === 0).toBe(true);
    host.destroy();
  });

  it('is absent when everybody was asked — there was nobody left', async () => {
    const host = fresh(33);
    const session = await shop(host, [0, 1, 2, 3]);
    expect(session.ghost).toBeNull();
    host.destroy();
  });

  it('changes no payout', async () => {
    const host = fresh(44);
    const session = await shop(host, [3]);
    expect(session.payoutBase).toBe(payoutBase(STAKE, session.bestBp, feesForMask(session.askedMask)));
    host.destroy();
  });

  it('is never dramatised — no exclamation, no "so close", anywhere in the copy', () => {
    const forbidden = [/!/, /so close/i, /almost/i, /unlucky/i, /bad luck/i, /if only/i, /jackpot/i, /congratulat/i];
    for (const value of everyString(COPY)) {
      for (const pattern of forbidden) expect(pattern.test(value), `"${value}" matches ${pattern}`).toBe(false);
    }
    expect(COPY.ghostNote).toMatch(/changed nothing/i);
  });
});

describe('a price does not exist before its fee is owed', () => {
  it('the ask sets the fee, and only then does a price arrive', async () => {
    const host = createDemoBrokersHost({ seed: [7, 7, 7, 7], randomnessDelayMs: 40 });
    await host.openSession(STAKE);
    await nextView(host, ready);
    const before = host.snapshot().session;
    const namedBefore = before?.named.length ?? 0;

    await host.submitAction({ kind: 'ASK', brokerId: 0 });
    // Mid-flight: the fee is owed, the man is looking, and nothing is named yet.
    const looking = host.snapshot().session;
    expect(looking?.waitingOn).toBe(0);
    expect(feesForMask(looking?.askedMask ?? 0)).toBe(BROKER_LIST[0]?.feeBp);
    expect(looking?.named.length).toBe(namedBefore);

    const after = await nextView(host, v => (v.session?.named.length ?? 0) > namedBefore);
    expect(after.session?.waitingOn).toBeNull();
    host.destroy();
  });

  it('the best price in hand only ever goes up', async () => {
    const host = fresh(55);
    await host.openSession(STAKE);
    let previous = 0;
    for (const broker of BROKER_LIST) {
      const view = await nextView(host, ready);
      const best = view.session?.bestBp ?? 0;
      expect(best, `after ${broker.name}`).toBeGreaterThanOrEqual(previous);
      previous = best;
      await host.submitAction({ kind: 'ASK', brokerId: broker.id });
    }
    host.destroy();
  });

  it('refuses a second look from the same man', async () => {
    const host = fresh(66);
    await host.openSession(STAKE);
    await nextView(host, ready);
    await host.submitAction({ kind: 'ASK', brokerId: 1 });
    await nextView(host, ready);
    await expect(host.submitAction({ kind: 'ASK', brokerId: 1 })).rejects.toThrow();
    host.destroy();
  });
});

describe('the purse', () => {
  it('escrows the stake and pays the one payout rule, exactly', async () => {
    const host = fresh(88);
    const opening = host.snapshot().purseBase ?? 0n;
    expect(opening).toBe(DEMO_OPENING_PURSE);

    const session = await shop(host, [2, 3]);
    const expected = payoutBase(STAKE, session.bestBp, feesForMask(session.askedMask));
    expect(session.payoutBase).toBe(expected);
    expect(host.snapshot().purseBase).toBe(opening - STAKE + expected);
    host.destroy();
  });

  it('never pays more than the best price less the one fee that buys it', async () => {
    const ceiling = payoutBase(STAKE, 50_000, BROKER_LIST[3]?.feeBp ?? 0);
    const host = fresh(121);
    for (let round = 0; round < 40; round++) {
      const ids = BROKER_LIST.slice(0, round % (BROKER_LIST.length + 1)).map(b => b.id);
      const session = await shop(host, ids);
      expect(session.payoutBase).toBeLessThanOrEqual(ceiling);
      host.dealAgain();
    }
    host.destroy();
  }, 20_000);

  it('and never pays nothing — there is no losing state', async () => {
    const worst = payoutBase(STAKE, Math.min(...HOUSE.map(q => q.priceBp)), feesForMask(15));
    expect(worst).toBeGreaterThan(0n);

    const host = fresh(131);
    for (let round = 0; round < 20; round++) {
      const session = await shop(host, BROKER_LIST.map(b => b.id));
      expect(session.payoutBase).toBeGreaterThanOrEqual(worst);
      host.dealAgain();
    }
    host.destroy();
  }, 20_000);

  it('refuses a stake below the minimum or above the purse', async () => {
    const host = fresh(99);
    await expect(host.openSession(DEMO_MIN_STAKE - 1n)).rejects.toThrow();
    await expect(host.openSession(DEMO_OPENING_PURSE + 1n)).rejects.toThrow();
    host.destroy();
  });

  it('refills to the opening purse, because it lasts one page load', async () => {
    const host = fresh(111);
    await shop(host, []);
    host.dealAgain();
    host.refill?.();
    expect(host.snapshot().purseBase).toBe(DEMO_OPENING_PURSE);
    host.destroy();
  });
});

describe('the same seed shops the same floor', () => {
  it('so a reported round can be reproduced, and a demo can be recorded', async () => {
    const play = async () => {
      const host = fresh(1728);
      const rows: string[] = [];
      for (let round = 0; round < 6; round++) {
        const session = await shop(host, [2, 3]);
        rows.push(`${session.bestBp}:${session.askedMask}:${session.payoutBase}:${session.ghost?.priceBp ?? '-'}`);
        host.dealAgain();
      }
      host.destroy();
      return rows.join('|');
    };
    expect(await play()).toBe(await play());
  });
});
