/**
 * The generated pages — the sixteen documents `npm run gen:pages` writes.
 *
 * `scripts/gates.mjs` checks the three `how` entry leaves because those are the
 * ones the door used to link to directly. It does not know the rest of the set
 * exists, and CI only checks that generated files are not STALE — a page that
 * was never written is not stale, and a link to a page that was never written
 * is not stale either. Both would ship silently.
 *
 * So this is the shape test for the whole set: that every page a URL on this
 * origin promises actually exists, that none of them quietly became an entry or
 * an application, and that no link on any of them points at nothing. The last
 * one is the reason the file exists — the four leaves navigate to each other by
 * a path built from a slug and a segment, and one wrong segment is a dead link
 * on twelve pages that nothing else in this repository would notice.
 */
import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { GAMES } from '../src/lobby/catalogue';

const ROOT = resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
const PUBLIC = resolve(ROOT, 'public');

/** The four leaves, in the order they are read. The first IS `how/`. */
const LEAVES = ['', 'table', 'band', 'check'] as const;

/** Every generated document, by the URL it is served at. */
const DOCUMENTS: readonly string[] = [
  '/verify/',
  ...GAMES.flatMap(game => [`/${game.slug}/about/`, ...LEAVES.map(at => `/${game.slug}/how/${at ? `${at}/` : ''}`)]),
];

/** Where a served URL lives on disk. `/x/` is `public/x/index.html`. */
const fileFor = (url: string): string => resolve(PUBLIC, `.${url}`, 'index.html');

const read = (url: string): string => readFileSync(fileFor(url), 'utf8');

describe('the generated pages', () => {
  it('there are sixteen of them, and the set is what the URLs promise', () => {
    expect(DOCUMENTS).toHaveLength(16);
    for (const url of DOCUMENTS) {
      expect(existsSync(fileFor(url)), `${url} was never written — run npm run gen:pages`).toBe(true);
    }
  });

  it('every one is marked generated, so nobody hand-edits one', () => {
    for (const url of DOCUMENTS) {
      expect(read(url), url).toContain('GENERATED by npm run gen:pages');
    }
  });

  /**
   * Not an entry and not an application. The widget marks a submission and none
   * of these is submitted; a document that needs a framework to print a table is
   * a document that can break, and these are the pages a judge reads to decide
   * whether the numbers are real.
   */
  it('none of them ships a script or a jam widget', () => {
    for (const url of DOCUMENTS) {
      const html = read(url);
      expect(html, `${url} ships JavaScript`).not.toMatch(/<script/i);
      expect(html, `${url} carries the widget`).not.toContain('jam.chain.wtf/widget.js');
    }
  });

  it('and every one can be left — back to the door, and on into a room', () => {
    for (const url of DOCUMENTS) {
      expect(read(url), url).toContain('href="/"');
    }
    for (const game of GAMES) {
      for (const at of LEAVES) {
        const url = `/${game.slug}/how/${at ? `${at}/` : ''}`;
        expect(read(url), url).toContain(`href="/${game.slug}/"`);
      }
      expect(read(`/${game.slug}/about/`)).toContain(`href="/${game.slug}/"`);
    }
  });
});

describe('the four leaves are a sequence', () => {
  it('each one marks where it is, and names all four', () => {
    for (const game of GAMES) {
      for (const [i, at] of LEAVES.entries()) {
        const html = read(`/${game.slug}/how/${at ? `${at}/` : ''}`);
        // The gathering mark for the leaf you are on is not a link out of it.
        expect(html, `${game.slug} leaf ${i}`).toContain('aria-current="page"');
        // And the other three are.
        const links = [...html.matchAll(/class="folio__link" href="([^"]+)"/g)].map(m => m[1]);
        expect(links, `${game.slug} leaf ${i}`).toHaveLength(LEAVES.length - 1);
      }
    }
  });

  it('the first leaf carries the declared return and its exact fraction', () => {
    for (const game of GAMES) {
      const html = read(`/${game.slug}/how/`);
      expect(html, game.slug).toContain('Returns, played best');
      expect(html, game.slug).toMatch(/Exactly \d+ \/ \d+/);
      expect(html, game.slug).toContain(game.rtp);
    }
  });
});

describe('nothing on this origin links at nothing', () => {
  it('every internal href on every generated page resolves to a file', () => {
    const broken: string[] = [];
    for (const url of DOCUMENTS) {
      for (const match of read(url).matchAll(/href="(\/[^"#?]*)"/g)) {
        const href = match[1]!;
        // A directory URL is served by its index.html; anything else is a file
        // in `public/` verbatim (the stylesheet, the favicon).
        const target = href.endsWith('/') ? resolve(PUBLIC, `.${href}`, 'index.html') : resolve(PUBLIC, `.${href}`);
        // The three game pages are built by Vite from `<slug>/index.html` at the
        // repo root, not from `public/`, so they are checked where they live.
        const built = resolve(ROOT, `.${href}`, 'index.html');
        if (!existsSync(target) && !existsSync(built)) broken.push(`${url} -> ${href}`);
      }
    }
    expect(broken).toEqual([]);
  });
});
